#!/bin/zsh
set -euo pipefail

SCRIPT_DIR="${0:A:h}"
IOS_ROOT="${SCRIPT_DIR:h}"
SOURCE_ROOT="$IOS_ROOT/.build/core-build/sing-box/sing-box"
OUTPUT_PATH="${1:-$IOS_ROOT/THIRD_PARTY_MODULES.txt}"
SING_BOX_COMMIT="1086ab2563320e0da0c23b3a491d8dfa0939dff4"

source "$SCRIPT_DIR/bootstrap-go.sh"

if [[ ! -d "$SOURCE_ROOT/.git" ]]; then
  mkdir -p "${SOURCE_ROOT:h}"
  git clone https://github.com/SagerNet/sing-box.git "$SOURCE_ROOT"
fi

git -C "$SOURCE_ROOT" fetch --tags --force
git -C "$SOURCE_ROOT" checkout --detach "$SING_BOX_COMMIT"

if [[ "$(git -C "$SOURCE_ROOT" rev-parse HEAD)" != "$SING_BOX_COMMIT" ]]; then
  print -u2 "Unexpected sing-box source commit."
  exit 1
fi

export GOMODCACHE="$IOS_ROOT/.build/go/pkg/mod"
export GOCACHE="$IOS_ROOT/.build/go/cache"
export GOPATH="$IOS_ROOT/.build/go/path"
export GOPROXY="${GOPROXY:-https://goproxy.cn,direct}"
mkdir -p "$GOMODCACHE" "$GOCACHE" "$GOPATH"

temporary_output="$(mktemp "${TMPDIR:-/tmp}/routeva-go-modules.XXXXXX")"
{
  print "# Generated by Scripts/generate-go-module-manifest.sh"
  print "# sing-box commit $SING_BOX_COMMIT"
  print "# Format: Go module path followed by the resolved version"
  (
    cd "$SOURCE_ROOT"
    "$ROUTEVA_GO_ROOT/bin/go" list -mod=readonly -m all | LC_ALL=C sort
  )
} > "$temporary_output"

mkdir -p "${OUTPUT_PATH:h}"
mv "$temporary_output" "$OUTPUT_PATH"
print "Wrote $OUTPUT_PATH"
